language: node_js
node_js:
  - "6"
  - "7"
  - "node"
before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
script: yarn test
notifications:
  email: false
cache:
  yarn: true
