language: node_js
node_js:
  - "4"
  - "4.1"
  - "4.2.4"
  - "4.3"
  - "4.4"
  - "5"
  - "5.10"
  - "5.11"
  - "6"
  - "6.1"
  - "node"
before_install:
  - npm install -g yarn
install:
  - yarn
script:
  - yarn test
notifications:
  email: false
