language: node_js
node_js:
  - '8'
  - '10'
  - '12'
matrix:
  fast_finish: true
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn install --ignore-engines --frozen-lockfile
before_script:
  - yarn run setup
script:
  - yarn test -w 2
notifications:
  email: false
cache:
  yarn: true
