language: node_js
node_js:
  - '8'
  - '10'
  - 'node'
before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn install --frozen-lockfile
  - yarn run setup
script: yarn test --maxWorkers=4
notifications:
  email: false
cache:
  yarn: true
