// flow-typed signature: 54667ba3615b447ea96bc145d9b78420
// flow-typed version: <<STUB>>/json5_v^0.5.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json5'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'json5' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'json5/lib/cli' {
  declare module.exports: any;
}

declare module 'json5/lib/json5' {
  declare module.exports: any;
}

declare module 'json5/lib/require' {
  declare module.exports: any;
}

// Filename aliases
declare module 'json5/lib/cli.js' {
  declare module.exports: $Exports<'json5/lib/cli'>;
}
declare module 'json5/lib/json5.js' {
  declare module.exports: $Exports<'json5/lib/json5'>;
}
declare module 'json5/lib/require.js' {
  declare module.exports: $Exports<'json5/lib/require'>;
}
