// flow-typed signature: 0866ed9a4f54b8bdd490c91d54cebcf0
// flow-typed version: <<STUB>>/log-update_v^2.3.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'log-update'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'log-update' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'log-update/index' {
  declare module.exports: $Exports<'log-update'>;
}
declare module 'log-update/index.js' {
  declare module.exports: $Exports<'log-update'>;
}
