name: Build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [16, 18, 20]
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
      - run: moon ci --color
        env:
          MOONBASE_SECRET_KEY: ${{ secrets.MOONBASE_SECRET_KEY }}
          MOON_NODE_VERSION: ${{ matrix.node-version }}
          YARN_IGNORE_NODE: 1
  pack:
    name: Pack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
      - run: moon run :pack --color
        env:
          MOONBASE_SECRET_KEY: ${{ secrets.MOONBASE_SECRET_KEY }}
          YARN_IGNORE_NODE: 1
