name: Build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [10, 12, 14, 15]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --ignore-engines --frozen-lockfile
      - run: yarn global add packemon@0.11.1 --force
      - run: yarn run build
      - run: yarn run type
      - run: yarn run coverage
      - run: yarn run lint
  pack:
    name: Pack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      - run: yarn install --ignore-engines --frozen-lockfile
      - run: yarn global add packemon@0.11.1 --force
      - run: yarn run pack
