name: Build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [8, 10, 12, 13]
      fail-fast: true
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --ignore-engines --frozen-lockfile
      - run: yarn run build
      - run: yarn run type
      # Not sure why, but have to force exit here as the tests would hang.
      # --runInBand and --detectOpenHandles didn't help diagnose the issue.
      - run: yarn run coverage
        env:
          BOOSTJS_ENV: 'development'
      - run: yarn run eslint
